### ISSUE TITLE
My integration hasn't been updating since 2024.3.0

### ISSUE THREAD

**Issue by webxl** [TheHolyRoger/hass-cryptoinfo#8]
It could just be a coincidence but here's the error:
 ```
2024-03-13 12:31:13.115 ERROR (MainThread) [custom_components.cryptoinfo_advanced.const.const] CryptoinfoAdvanced error fetching update for Cryptoinfo BTC Price: TypeError: 'NoneType' object is not subscriptable
 2024-03-13 12:31:13.116 ERROR (MainThread) [custom_components.cryptoinfo_advanced.const.const] Traceback (most recent call last):
   File "/config/custom_components/cryptoinfo_advanced/crypto_sensor.py", line 735, in _async_api_fetch
     primary_data = extract_primary(api_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/cryptoinfo_advanced/crypto_sensor.py", line 753, in _extract_data_price_main_primary
     return api_data["current_price"] * float(self.multiplier)
            ~~~~~~~~^^^^^^^^^^^^^^^^^
 TypeError: 'NoneType' object is not subscriptable
 
 During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
   File "/config/custom_components/cryptoinfo_advanced/crypto_sensor.py", line 735, in _async_api_fetch
     primary_data = extract_primary(api_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/config/custom_components/cryptoinfo_advanced/crypto_sensor.py", line 759, in _extract_data_price_simple_primary
     return api_data[self.currency_name] * float(self.multiplier)
            ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

If I scroll back a little I see `Error fetching update from coingecko: Expecting property name enclosed in double quotes: line 1 column 3 (char 2) - response status: 403 - Forbidden`

**Comment by webxl** [comment]
This looks like a VPN issue.
